"""add google auth fields

Revision ID: 0902dbd5c2d3
Revises: dc9e236ad3b5
Create Date: 2026-06-23 11:30:40.891302

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0902dbd5c2d3'
down_revision: Union[str, Sequence[str], None] = 'dc9e236ad3b5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('google_token_expiry', sa.DateTime(), nullable=True))
    op.add_column('users', sa.Column('last_login_at', sa.DateTime(), nullable=True))
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_column('users', 'last_sync_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('last_sync_at', sa.DATETIME(), nullable=True))
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=1)
    op.drop_column('users', 'last_login_at')
    op.drop_column('users', 'google_token_expiry')
    # ### end Alembic commands ###
