"""update_models_and_column_mappings

Revision ID: 442dd66f6dcc
Revises: 8f07dd7996da
Create Date: 2026-07-29 17:50:40.064802

"""
from typing import Sequence, Union
import pgvector

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '442dd66f6dcc'
down_revision: Union[str, Sequence[str], None] = '8f07dd7996da'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('approvals', sa.Column('created_at', sa.DateTime(), nullable=False))
    op.add_column('approvals', sa.Column('updated_at', sa.DateTime(), nullable=False))
    op.create_unique_constraint(None, 'approvals', ['draft_reply_id'])
    op.create_foreign_key(None, 'approvals', 'draft_replies', ['draft_reply_id'], ['id'])
    op.add_column('draft_replies', sa.Column('user_id', sa.Integer(), nullable=True))
    op.add_column('draft_replies', sa.Column('version', sa.Integer(), nullable=False))
    op.add_column('draft_replies', sa.Column('tone', sa.String(length=50), nullable=False))
    op.add_column('draft_replies', sa.Column('is_current', sa.Boolean(), nullable=False))
    op.add_column('draft_replies', sa.Column('gmail_draft_id', sa.String(length=255), nullable=True))
    op.add_column('draft_replies', sa.Column('is_sent', sa.Boolean(), nullable=False))
    op.add_column('draft_replies', sa.Column('sent_at', sa.DateTime(), nullable=True))
    op.add_column('draft_replies', sa.Column('created_at', sa.DateTime(), nullable=False))
    op.add_column('draft_replies', sa.Column('updated_at', sa.DateTime(), nullable=False))
    op.alter_column('draft_replies', 'draft',
               existing_type=sa.VARCHAR(),
               type_=sa.Text(),
               existing_nullable=False)
    op.create_index(op.f('ix_draft_replies_email_id'), 'draft_replies', ['email_id'], unique=False)
    op.create_index(op.f('ix_draft_replies_user_id'), 'draft_replies', ['user_id'], unique=False)
    op.create_foreign_key(None, 'draft_replies', 'emails', ['email_id'], ['id'])
    
    # -------------------------------------------------------------
    # 1. DROP INDEXES FIRST (HNSW indexes block column alterations)
    # -------------------------------------------------------------
    op.drop_constraint(op.f('email_embeddings_email_id_key'), 'email_embeddings', type_='unique')
    op.drop_index(op.f('email_embeddings_email_idx'), table_name='email_embeddings')
    op.drop_index(op.f('email_embeddings_metadata_idx'), table_name='email_embeddings', postgresql_using='gin')
    op.drop_index(op.f('email_embeddings_vector_idx'), table_name='email_embeddings', postgresql_ops={'embedding': 'vector_cosine_ops'}, postgresql_using='hnsw')

    # -------------------------------------------------------------
    # 2. CLEAR EXISTING 384-DIM DATA TO ALLOW TYPE CONVERSION
    # -------------------------------------------------------------
    op.execute("TRUNCATE TABLE email_embeddings;")

    # -------------------------------------------------------------
    # 3. ALTER COLUMNS NOW THAT TABLE IS EMPTY
    # -------------------------------------------------------------
    op.alter_column('email_embeddings', 'id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('email_embeddings', 'embedding',
               existing_type=pgvector.sqlalchemy.vector.VECTOR(dim=384),
               type_=pgvector.sqlalchemy.vector.VECTOR(dim=1536),
               nullable=False)
    op.alter_column('email_embeddings', 'metadata',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=False,
               existing_server_default=sa.text("'{}'::jsonb"))
               
    op.create_index(op.f('ix_email_embeddings_email_id'), 'email_embeddings', ['email_id'], unique=True)
    # ### end Alembic commands ###



def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_email_embeddings_email_id'), table_name='email_embeddings')
    op.create_index(op.f('email_embeddings_vector_idx'), 'email_embeddings', ['embedding'], unique=False, postgresql_ops={'embedding': 'vector_cosine_ops'}, postgresql_using='hnsw')
    op.create_index(op.f('email_embeddings_metadata_idx'), 'email_embeddings', ['metadata'], unique=False, postgresql_using='gin')
    op.create_index(op.f('email_embeddings_email_idx'), 'email_embeddings', ['email_id'], unique=False)
    op.create_unique_constraint(op.f('email_embeddings_email_id_key'), 'email_embeddings', ['email_id'], postgresql_nulls_not_distinct=False)
    op.alter_column('email_embeddings', 'metadata',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=False,
               existing_server_default=sa.text("'{}'::jsonb"))
    op.alter_column('email_embeddings', 'embedding',
               existing_type=pgvector.sqlalchemy.vector.VECTOR(dim=1536),
               type_=pgvector.sqlalchemy.vector.VECTOR(dim=384),
               nullable=True)
    op.alter_column('email_embeddings', 'id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=False,
               autoincrement=True)
    op.drop_constraint(None, 'draft_replies', type_='foreignkey')
    op.drop_index(op.f('ix_draft_replies_user_id'), table_name='draft_replies')
    op.drop_index(op.f('ix_draft_replies_email_id'), table_name='draft_replies')
    op.alter_column('draft_replies', 'draft',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(),
               existing_nullable=False)
    op.drop_column('draft_replies', 'updated_at')
    op.drop_column('draft_replies', 'created_at')
    op.drop_column('draft_replies', 'sent_at')
    op.drop_column('draft_replies', 'is_sent')
    op.drop_column('draft_replies', 'gmail_draft_id')
    op.drop_column('draft_replies', 'is_current')
    op.drop_column('draft_replies', 'tone')
    op.drop_column('draft_replies', 'version')
    op.drop_column('draft_replies', 'user_id')
    op.drop_constraint(None, 'approvals', type_='foreignkey')
    op.drop_constraint(None, 'approvals', type_='unique')
    op.drop_column('approvals', 'updated_at')
    op.drop_column('approvals', 'created_at')
    # ### end Alembic commands ###
