"""upgrade_chat_history_model_01

Revision ID: d1d9ef284361
Revises: 27cfee31c41b
Create Date: 2026-07-04 10:06:16.701350

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd1d9ef284361'
down_revision: Union[str, Sequence[str], None] = '27cfee31c41b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_chat_history_created_at'), 'chat_history', ['created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_chat_history_created_at'), table_name='chat_history')
    # ### end Alembic commands ###
