from __future__ import annotations

from typing import Literal

from pydantic import BaseModel, Field

from langchain_core.output_parsers import PydanticOutputParser
from langchain_core.prompts import ChatPromptTemplate

from backend.app.core.llm import llm


class QueryPlan(BaseModel):
    """
    Structured execution plan generated by the LLM.
    """

    intent: Literal[
        "semantic_search",
        "summarize",
        "sender_lookup",
        "deadline_search",
        "metadata_search",
    ] = Field(
        description="Overall user intent."
    )

    semantic_query: str | None = Field(
    default=None,
    description="Optimized semantic search query.",
)

    category: str | None = Field(
        default=None,
        description="Email category filter if applicable.",
    )

    priority: str | None = Field(
        default=None,
        description="Priority filter if applicable.",
    )

    sender: str | None = Field(
        default=None,
        description="Sender filter if user asked for a specific person.",
    )

    needs_reply: bool | None = Field(
        default=None,
        description="Whether to filter emails requiring replies.",
    )

    retrieve_limit: int = Field(
        default=5,
        ge=1,
        le=50,
        description="Maximum number of emails to retrieve.",
    )

    sort_by: Literal[
        "relevance",
        "date",
        "priority",
    ] = Field(
        default="relevance",
        description="How retrieved emails should be ordered.",
    )

    date_from: str | None = Field(
        default=None,
        description="ISO date string for earliest email to search.",
    )

    date_to: str | None = Field(
        default=None,
        description="ISO date string for latest email to search.",
    )

    reasoning: str = Field(
        description="Brief explanation of why this retrieval plan was chosen.",
    )


class QueryPlanner:
    """
    Uses an LLM to transform a natural language inbox question
    into a structured retrieval plan.
    """

    def __init__(self):

        self.parser = PydanticOutputParser(
            pydantic_object=QueryPlan,
        )

        self.prompt = ChatPromptTemplate.from_messages(
            [
                (
                    "system",
                    """
You are an expert retrieval planner for an AI Email Assistant.

Your ONLY responsibility is to create the best retrieval plan.

DO NOT answer the user's question.

Return ONLY valid JSON that follows the provided schema.

----------------------------------------
Available intents
----------------------------------------

semantic_search
summarize
sender_lookup
deadline_search
metadata_search

----------------------------------------
Planning Guidelines
----------------------------------------

semantic_search
- General semantic retrieval.
- Rewrite vague questions into better search queries.

summarize
- User wants an overview or summary.
- Retrieve more emails.
- Usually retrieve_limit = 20.

sender_lookup
- User is asking who sent something,
or asks about a particular sender.
- Populate sender when possible.
- Usually retrieve_limit = 10.

deadline_search
- Questions involving:
    deadlines
    due dates
    interviews
    events
    meetings
    appointments
- Populate date_from/date_to if possible.
- Usually retrieve_limit = 10.
- Prefer sort_by="date".

metadata_search
- User explicitly filters by:
    category
    priority
    reply requirement
    sender
or other structured metadata.

----------------------------------------
Metadata Rules
----------------------------------------

Populate these whenever possible:

category
priority
sender
needs_reply
date_from
date_to

If unavailable, return null.

----------------------------------------
Sorting Rules
----------------------------------------

Default:

sort_by = "relevance"

If user asks for:

latest
recent
newest

→ sort_by = "date"

If user asks:

highest priority
urgent

→ sort_by = "priority"

----------------------------------------
Retrieve Limit Rules
----------------------------------------

Normal search:

5

Sender lookup:

10

Deadline search:

10

Summary:

20

----------------------------------------
Examples
----------------------------------------

Question:
Summarize finance emails.

intent:
summarize

category:
finance

retrieve_limit:
20

sort_by:
date

----------------------------------------

Question:
Who emailed me about internships?

intent:
sender_lookup

semantic_query:
internship opportunities

retrieve_limit:
10

----------------------------------------

Question:
Which emails require replies?

intent:
metadata_search

needs_reply:
true

----------------------------------------

Question:
Any deadlines this week?

intent:
deadline_search

sort_by:
date

----------------------------------------

Question:
Show my latest recruiter emails.

intent:
metadata_search

category:
recruitment

sort_by:
date

----------------------------------------

{format_instructions}
""",
                ),
                (
                    "human",
                    "{question}",
                ),
            ]
        )

    async def plan(
        self,
        question: str,
    ) -> QueryPlan:

        chain = (
            self.prompt.partial(
                format_instructions=self.parser.get_format_instructions(),
            )
            | llm
            | self.parser
        )

        return await chain.ainvoke(
            {
                "question": question,
            }
        )