from __future__ import annotations

from typing import Literal

from pydantic import BaseModel
from pydantic import Field

from langchain_core.output_parsers import PydanticOutputParser
from langchain_core.prompts import ChatPromptTemplate

from backend.app.core.llm import llm


class QueryPlan(BaseModel):
    """
    Structured retrieval plan generated by the LLM.

    This object is consumed by ChatRetriever to perform
    semantic retrieval and metadata filtering.
    """

    intent: Literal[
        "semantic_search",
        "summarize",
        "sender_lookup",
        "deadline_search",
        "metadata_search",
    ] = Field(
        description="Overall intent of the user's request."
    )

    semantic_query: str | None = Field(
        default=None,
        description=(
            "Optimized semantic search query. "
            "Rewrite vague user questions into better search phrases."
        ),
    )

    category: str | None = Field(
        default=None,
        description="Email category filter.",
    )

    priority: Literal[
        "low",
        "medium",
        "high",
        "urgent",
    ] | None = Field(
        default=None,
        description="Priority filter.",
    )

    sender: str | None = Field(
        default=None,
        description="Specific sender if requested.",
    )

    requires_reply: bool | None = Field(
        default=None,
        description=(
            "Whether only emails requiring a reply "
            "should be returned."
        ),
    )

    retrieve_limit: int = Field(
        default=5,
        ge=1,
        le=50,
        description="Maximum number of emails to retrieve.",
    )

    sort_by: Literal[
        "relevance",
        "date",
        "priority",
    ] = Field(
        default="relevance",
        description="Sorting strategy.",
    )

    date_from: str | None = Field(
        default=None,
        description="Inclusive ISO date lower bound.",
    )

    date_to: str | None = Field(
        default=None,
        description="Inclusive ISO date upper bound.",
    )

    reasoning: str = Field(
        description="Short explanation of the chosen retrieval plan.",
    )


class QueryPlanner:
    """
    Converts a natural language inbox question into
    a structured QueryPlan.

    Responsibilities
    ----------------
    - Classify user intent
    - Detect metadata filters
    - Rewrite semantic queries
    - Select retrieval size
    - Select sorting strategy
    - Detect sender filters
    - Detect date filters

    This class NEVER answers the user's question.
    It ONLY creates a retrieval plan.
    """

    def __init__(self):

        self.parser = PydanticOutputParser(
            pydantic_object=QueryPlan,
        )

        self.prompt = ChatPromptTemplate.from_messages(
            [
                (
                    "system",
                    """
You are the Retrieval Planning Engine for INQUIREA.

Your ONLY responsibility is to transform a user's inbox question

into a structured QueryPlan.

You NEVER answer the user's question.

You NEVER summarize emails.

You NEVER invent facts.

Return ONLY valid JSON matching the provided schema.

========================================================

AVAILABLE INTENTS

========================================================

1. semantic_search

2. summarize

3. metadata_search

4. sender_lookup

5. deadline_search

Choose exactly ONE intent.

========================================================

GENERAL PLANNING RULES

========================================================

Your job is to decide:

• which intent best matches the request

• whether semantic search is required

• whether metadata filters are needed

• how many emails should be retrieved

• how results should be sorted

• whether sender/category/priority/date filters exist

Do NOT answer the question.

Do NOT explain anything outside the JSON.

========================================================

SEMANTIC QUERY REWRITING

========================================================

Rewrite vague user questions into concise search queries.

Examples

User:

internship mails

semantic_query:

internship opportunities

----------------------------

User:

payment reminder

semantic_query:

payment reminder invoice due

----------------------------

User:

Amazon order

semantic_query:

amazon order purchase shipping

----------------------------

User:

job interview

semantic_query:

job interview interview invitation recruiter

If the original question is already a good search query,

reuse it.

========================================================

INTENT SELECTION

========================================================

semantic_search

Use for:

• normal questions

• topic search

• finding emails

Examples

Show internship emails.

Amazon receipts

Who mentioned payment?

Show invoices.

--------------------------------------------------------

summarize

Use whenever the user asks for:

summarize

overview

digest

recap

all updates

summary

Rules

retrieve_limit = 20

sort_by = date

--------------------------------------------------------

metadata_search

Use when the user explicitly filters by metadata.

Metadata includes

priority

category

requires_reply

sender

latest

recent

Examples

High priority emails

Medium priority

Urgent emails

Recruiter emails

Finance emails

Emails requiring replies

Unread invoices

Latest newsletters

--------------------------------------------------------

sender_lookup

Use when the user asks

Who emailed me...

Who sent...

Emails from...

Messages by...

Populate sender whenever possible.

retrieve_limit = 10

--------------------------------------------------------

deadline_search

Use for

deadline

due

meeting

calendar

appointment

event

interview

submission

assignment

schedule

retrieve_limit = 10

sort_by = date

Populate date_from/date_to whenever possible.

========================================================

CATEGORY DETECTION

========================================================

Populate category when obvious.

Examples

finance

recruitment

shopping

travel

social

education

banking

promotion

newsletter

github

receipts

If unknown

category = null

========================================================

PRIORITY DETECTION

========================================================

Only use

low

medium

high

urgent

Examples

high priority

priority emails

urgent mail

low priority

medium priority

Otherwise

priority = null

========================================================

REQUIRES REPLY DETECTION

========================================================

IMPORTANT

Your output field is

requires_reply

NOT

needs_reply

Populate

requires_reply = true

when the user asks

requires reply

need reply

reply pending

awaiting response

emails to respond

emails I should reply to

reply required

Otherwise

requires_reply = null

========================================================

DATE DETECTION

========================================================

Recognize phrases like

today

yesterday

last week

this week

this month

last month

recent

latest

newest

When possible

populate

date_from

date_to

Use ISO dates if they can be inferred.

If impossible

return null.

========================================================

SORTING RULES

========================================================

Default

sort_by = relevance

If user asks

latest

recent

newest

sort_by = date

If user asks

highest priority

urgent

sort_by = priority

========================================================

RETRIEVE LIMIT RULES

========================================================

Normal search

5

Metadata search

5

Sender lookup

10

Deadline search

10

Summary

20

Never exceed 50.

========================================================

EXAMPLES

========================================================

Question

Show my high priority emails.

intent:

metadata_search

priority:

high

retrieve_limit:

5

sort_by:

priority

--------------------------------------------------------

Question

Show medium priority emails.

intent:

metadata_search

priority:

medium

--------------------------------------------------------

Question

Show low priority emails.

intent:

metadata_search

priority:

low

--------------------------------------------------------

Question

Show urgent emails.

intent:

metadata_search

priority:

urgent

--------------------------------------------------------

Question

Which emails require replies?

intent:

metadata_search

requires_reply:

true

--------------------------------------------------------

Question

Summarize finance emails.

intent:

summarize

category:

finance

retrieve_limit:

20

sort_by:

date

--------------------------------------------------------

Question

Who emailed me about internships?

intent:

sender_lookup

semantic_query:

internship opportunities

retrieve_limit:

10

--------------------------------------------------------

Question

Any interview deadlines this week?

intent:

deadline_search

sort_by:

date

retrieve_limit:

10

--------------------------------------------------------

Question

Latest recruiter emails.

intent:

metadata_search

category:

recruitment

sort_by:

date

--------------------------------------------------------

Question

Amazon receipts

intent:

semantic_search

semantic_query:

amazon purchase receipt order

========================================================

OUTPUT REQUIREMENTS

========================================================

Return ONLY valid JSON.

Every field in the schema must be present.

Use null instead of omitting optional fields.

Do not wrap JSON in markdown.

{format_instructions}
""",
                ),
                (
                    "human",
                    "{question}",
                ),
            ]
        )
    async def plan(
        self,
        question: str,
    ) -> QueryPlan:
        """
        Generate a structured retrieval plan from a user's natural language
        inbox question.

        This method also performs validation and normalization to ensure
        downstream retrieval always receives a usable QueryPlan.
        """

        chain = (
            self.prompt.partial(
                format_instructions=self.parser.get_format_instructions(),
            )
            | llm
            | self.parser
        )

        try:
            plan: QueryPlan = await chain.ainvoke(
                {
                    "question": question,
                }
            )

        except Exception:
            # Safe fallback if the LLM or parser fails.
            return QueryPlan(
                intent="semantic_search",
                semantic_query=question,
                category=None,
                priority=None,
                sender=None,
                requires_reply=None,
                retrieve_limit=5,
                sort_by="relevance",
                date_from=None,
                date_to=None,
                reasoning="Fallback retrieval plan generated after planner failure.",
            )

        # --------------------------------------------------
        # Validation / Normalization
        # --------------------------------------------------

        # Use the original question if no semantic query was produced.
        if not plan.semantic_query:
            plan.semantic_query = question

        # Normalize priority.
        if plan.priority:
            plan.priority = plan.priority.lower().strip()

            allowed = {
                "low",
                "medium",
                "high",
                "urgent",
            }

            if plan.priority not in allowed:
                plan.priority = None

        # Normalize category.
        if plan.category:
            plan.category = plan.category.lower().strip()

        # Normalize sender.
        if plan.sender:
            plan.sender = plan.sender.strip()

        # Clamp retrieve_limit.
        plan.retrieve_limit = max(
            1,
            min(
                plan.retrieve_limit,
                50,
            ),
        )

        # Validate sorting.
        if plan.sort_by not in {
            "relevance",
            "date",
            "priority",
        }:
            plan.sort_by = "relevance"

        # Summaries should retrieve more emails.
        if (
            plan.intent == "summarize"
            and plan.retrieve_limit < 20
        ):
            plan.retrieve_limit = 20

        # Deadline searches should default to date sorting.
        if (
            plan.intent == "deadline_search"
            and plan.sort_by != "date"
        ):
            plan.sort_by = "date"

        return plan

